### ISSUE TITLE
Error Gives out code Details

### ISSUE THREAD

**Issue by satyarth934** [Swiftintern/Swiftintern#18]
Follow these steps:
1. Open 2 tabs.
2. Login as Admin on both
3. Open Admin Panel on both.
4. Select any of the options in Tab1.
5. Logout from Tab2.
6. Refresh Tab1.
7. You get an error message but you also get some of the code details.

I guess it'll be safer if we don't get those details.
I got to see this one. There might be more of this kind.

**Comment by faizanayubi** [comment]
Yes, the code is showing because we are in development mode currently will hide those after we technically resole all our issue on github

**Comment by faizanayubi** [comment]
done for admin panel

**Comment by satyarth934** [comment]
ok ok.
then it's cool.
