### ISSUE TITLE
Resume Making

### ISSUE THREAD

**Issue by faizanayubi** [Swiftintern/Swiftintern#2]
with live editing of resume feature after importing from Linkedin

**Comment by faizanayubi** [comment]
Have you tested it online? i have uploaded the script..
Is it working?

**Comment by Hemant-Mann** [comment]
The code works fine on my system. Have you comitted the changes to server?

**Comment by faizanayubi** [comment]
Yes i have uploaded it online, you can test it and tell me

**Comment by Hemant-Mann** [comment]
Doesn't seem to work. The file success.html on the server is different then one i last comitted in the repository

**Comment by faizanayubi** [comment]
Do you have it offline?
Commit Again? or see the file history

**Comment by faizanayubi** [comment]
Phone Number not working close this issue after completion

**Comment by faizanayubi** [comment]
All Done
