### ISSUE TITLE
swiftintern

### ISSUE THREAD

**Issue by uditv0** [Swiftintern/Swiftintern#21]
check this ...  
"http://swiftintern.com/organization/LG+Soft/experience/LG+SOFT+PATTERN+%26amp%3B+INTERVIEW+-+09+JAN+2009+-+NOIDA/1988 "

check the path ...
path : home > placemnt paper > choose company > profile > experience > read more

**Comment by faizanayubi** [comment]
Solved there was an error in URL
Try this : http://swiftintern.com/experience/LG+SOFT+PATTERN++INTERVIEW+-+09+JAN+2009+-+NOIDA/1988
