### ISSUE TITLE
Autocomplete Plugin

### ISSUE THREAD

**Issue by faizanayubi** [Swiftintern/Swiftintern#27]
Auto Search function to be assigned to following pages
http://swiftintern.com/placement-papers

**Comment by faizanayubi** [comment]
what is the status?
you told that you will complete it by wednesday

**Comment by sakshamsaxena** [comment]
It'll be complete by tonight. For now, it'll be taking the data in JSON form. I'll let you know the structure shortly.

-----Original Message-----

**Comment by faizanayubi** [comment]
okay cool 
JSON Data is more than enough for testing use below url
![capture](https://cloud.githubusercontent.com/assets/4982023/8594742/7e72cb66-2661-11e5-8b3b-2d929c2516f0.PNG)

**Comment by sakshamsaxena** [comment]
Alpha version ready. Testing with the above json is left. Will commit shortly.

**Comment by sakshamsaxena** [comment]
See 0d7e6185f7a6d0c2a0f2f185ca1f4c02406ddd04
