### ISSUE TITLE
Getting error while creating resume

### ISSUE THREAD

**Issue by saudaktr** [Swiftintern/Swiftintern#30]
![resume](https://cloud.githubusercontent.com/assets/9394007/8539867/090854e6-249e-11e5-9140-b3668650a469.png)

Kindly find the attached file.

**Comment by Hemant-Mann** [comment]
Can you describe how the bug occurs?

**Comment by faizanayubi** [comment]
while saving education qualification as you can see in the  pic

**Comment by Hemant-Mann** [comment]
I am calling 'saveQual' function in students controller which you had written

**Comment by faizanayubi** [comment]
Resolved
