### ISSUE TITLE
Profile Link not working in mail which is received after quick applying.

### ISSUE THREAD

**Issue by saudaktr** [Swiftintern/Swiftintern#35]
It is redirecting to some other website and giving 404. the redirected Link is :https://www.student.com/applications

This is the received email
![mail](https://cloud.githubusercontent.com/assets/9394007/8767414/b6fcdace-2e79-11e5-8da2-7838b806b2c9.PNG)

This is the redirected page.
![redi](https://cloud.githubusercontent.com/assets/9394007/8767408/93e55c14-2e79-11e5-9e85-eb7964f3ce98.png)

**Comment by faizanayubi** [comment]
Improved
