### ISSUE TITLE
Log in button 

### ISSUE THREAD

**Issue by uditv0** [Swiftintern/Swiftintern#36]
Add google+ as a login option

**Comment by faizanayubi** [comment]
Integrate Google+ Login Only for Students Should be completed by 23rd july
Data to take
1. Name
2. Email
3. Phone(if exists)
4. Education Qualification(if exists)
5 Work Experience(if exists)

Used to
1. Register Students
2. Create resume

**Comment by Hemant-Mann** [comment]
Google+ Login Added to site. Everyone plz check and report for bugs if any

**Comment by Hemant-Mann** [comment]
Login complete!
