### ISSUE TITLE
Student Signup with LinkedIn & Google not working

### ISSUE THREAD

**Issue by codehimanshu** [Swiftintern/Swiftintern#42]
The signup buttons on http://swiftintern.com/students/register are not redirecting to the Providers Auth page.
![SignUp Page](https://cloud.githubusercontent.com/assets/14791631/20856584/42ee27f0-b938-11e6-8c0c-9f36958097f0.png)
Employer Registrations are working fine.

**Comment by Hemant-Mann** [comment]
Hi There the buttons are redirecting correct but there was some issue with new user registeration - which I fixed in the last commit

**Comment by faizanayubi** [comment]
Thanks @Hemant-Mann
